# Generated by Django 5.1.7 on 2026-06-14 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sender_name', models.CharField(max_length=120)),
                ('recipient_name', models.CharField(max_length=120)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('on_hold', 'On Hold')], default='order_received', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('on_hold', 'On Hold')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.shipment')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
