# Generated by Django 5.1.7 on 2026-06-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='goods_dimensions',
            field=models.CharField(default=4, help_text='Dimensions in cm', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_height',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Height in cm', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_length',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Length in cm', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_type',
            field=models.CharField(default=1, help_text='Type of goods', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Value in Pounds', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='goods_width',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Width in cm', max_digits=8),
            preserve_default=False,
        ),
    ]
